# docker-compose file for running testing with gotenberg container
# Can be used locally or by the CI to start the nessecary container with the
# correct networking for the tests

version: "3"
services:
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.9.2
    hostname: gotenberg
    container_name: gotenberg
    network_mode: host
    restart: unless-stopped
